config/routes.rb
Funappforquiztwo::Application.routes.draw do
  root 'shoes#index'

  resources :shoes

end

app/models/shoes.rb
class Shoes < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
	def index
		@shoes = Shoes.first
	end

	def new
		@shoes = Shoes.new
	end

	 def create
   Shoes.create(Shoes_params)
  end

  private

  def Shoes_params
    params.require(:shoes).permit(:name, :brand)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Funappforquiztwo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>

<header>
<div class="col-xs-3">
	<%= link_to root_path, :class => 'logo' do %>
	<div class="circle">
	Logo
	<% end %>

</div>

<div class="col-xs-4">
	Nice Time
</div>

<div class="col-xs-5 links">
	<%= link_to 'Contribute', new_shoe_path %>

</header>

</html>

app/views/shoes/index.html.erb
<h1>Welcome to my app</h1>

<h1> <%= @shoes.name %></h1>
<h2> <%= @shoes.brand %></h1>

app/views/shoes/new.html.erb
<h1>Enter Your Quote Details</h1>
<%= simple_form_for :shoes do |f| %>
  <%= f.input :name %>
  <%= f.input :brand %>
  <%= f.submit 'Create', :class => 'btn btn-danger', :method => :POST %>
<% end %>